### ISSUE TITLE
DOMException when clicking a link

### ISSUE THREAD

**Issue by sburkett** [FriendsOfFlarum/links#30]
So, I have a custom Flarum home page (using `fof/pages`), so the forums aren't seen when you first get to the site. I have a "Forums" link in the navbar (created with `fof/links`, of course!), which simply sends the user to the `http://site.com/all` route.

When I click on it from the navbar, it fails to load, and I get this in the console:

```
router.js:24 Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'http://site.com/all' cannot be created in a document with origin 'http://site' and URL 'http://site.com/all'.
    at p (http://site.com/assets/forum-f5cae522.js:25:106516)
    at Function.y.set (http://site.com/assets/forum-f5cae522.js:25:108543)
    at HTMLAnchorElement.s.attrs.onclick (http://site.com/assets/forum-f5cae522.js:25:109364)
    at _.handleEvent (http://site.com/assets/forum-f5cae522.js:25:102087)
```

Note in the above, the issue is that the origin is `http://site` and the URL is `http://site.com/all`. I'm thinking `http://site` should actually be `http://site.com`.

I cleared the cache, et al as well.

To try and determine if this is actually an issue with `fof/links` , `flarum/core`, or some other extension, I did the following, both of which worked:

* Manually tested the link in the browser
* Added the link to a page from `fof/pages` and clicked on that

Update: I should have added that this was working fine earlier today, prior to upgrading Flarum from beta 13 to beta 15.

Here is some other info, if this helps:

```
Flarum core 0.1.0-beta.15
PHP version: 7.2.34
Loaded extensions: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, libsodium, apcu, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, fileinfo, ftp, gd, geoip, gettext, gmp, iconv, igbinary, imagick, json, exif, mysqlnd, mysqli, odbc, PDO, pdo_dblib, pdo_mysql, PDO_ODBC, pdo_sqlite, Phar, posix, pspell, recode, redis, shmop, SimpleXML, snmp, soap, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xdiff, xml, wddx, xmlreader, xmlwriter, xsl, memcached, zip, Zend OPcache, xdebug
+------------------------------+----------------+--------+
| Flarum Extensions            |                |        |
+------------------------------+----------------+--------+
| ID                           | Version        | Commit |
+------------------------------+----------------+--------+
| flarum-lang-english          | v0.1.0-beta.15 |        |
| flarum-sticky                | v0.1.0-beta.15 |        |
| flarum-tags                  | v0.1.0-beta.15 |        |
| fof-byobu                    | 0.6.0          |        |
| fof-drafts                   | 0.3.1          |        |
| fof-polls                    | 0.3.2          |        |
| fof-reactions                | 0.5.0          |        |
| flarum-likes                 | v0.1.0-beta.15 |        |
| flarum-mentions              | v0.1.0-beta.15 |        |
| flarum-subscriptions         | v0.1.0-beta.15 |        |
| flarum-emoji                 | v0.1.0-beta.15 |        |
| flarum-flags                 | v0.1.0-beta.15 |        |
| flarum-approval              | v0.1.0-beta.15 |        |
| fof-merge-discussions        | 0.5.1          |        |
| fof-pages                    | 0.6.0          |        |
| fof-masquerade               | 0.3.6          |        |
| flarum-suspend               | v0.1.0-beta.15 |        |
| flarum-lock                  | v0.1.0-beta.15 |        |
| fof-split                    | 0.6.0          |        |
| fof-forum-statistics-widget  | 0.4.0          |        |
| fof-profile-image-crop       | 0.2.1          |        |
| fof-user-bio                 | 0.4.1          |        |
| fof-user-directory           | 0.5.0          |        |
| flarum-statistics            | v0.1.0-beta.15 |        |
| fof-formatting               | 0.3.1          |        |
| flarum-markdown              | v0.1.0-beta.15 |        |
| nearata-tags-color-generator | v1.2.0         |        |
| fof-links                    | 0.5.0          |        |
| fof-doorman                  | 0.3.0          |        |
| fof-terms                    | 0.6.1          |        |
| flarum-bbcode                | v0.1.0-beta.15 |        |
+------------------------------+----------------+--------+
Base URL: http://site.com
Installation path: /var/www/tmv
Debug mode: off
```

Any thoughts?

**Comment by sburkett** [comment]
Yikes. Disregard. I should never do this sort of thing before my 2nd cup of coffee. The mistake was in the URL of the link entry in `fof/links`. I forgot the `.com` TLD ... whoops.

Closing, but leaving for posterity in case someone else ever runs into this.
